package io.github.alph_a07.basis.tokens.color

/**
 * Tuning parameters for categorical color generation.
 *
 * Covers the three levers the categorical engine pulls: the lightness the palette sits at in each
 * mode, the chroma floor that keeps generated series legible, and the scale factors that produce the
 * muted "soft" variant.
 */
data class BasisCategoricalTuning(
    /** Lightness applied to generated colors in light mode. */
    val paletteLightnessLight: Float = 0.65f,
    /** Lightness applied to generated colors in dark mode. */
    val paletteLightnessDark: Float = 0.72f,
    /** Lower bound on chroma, so a pale seed hue still yields a visible series. */
    val paletteMinChroma: Float = 0.14f,
    /** Lightness applied by [softVariant] in light mode. */
    val softLightnessLight: Float = 0.92f,
    /** Lightness applied by [softVariant] in dark mode. */
    val softLightnessDark: Float = 0.28f,
    /** Multiplier applied to each color's chroma by [softVariant]. */
    val softChromaScale: Float = 0.35f,
)

/**
 * Builds a single contrast-safe categorical color for one mode, given a non-empty list of seed hues.
 *
 * Indices within the seed range take their hue directly. Beyond the last seed, hues are generated by
 * rotating around the golden angle, so a request for more series than seeds stays visually distinct
 * instead of repeating.
 *
 * @param index The index of the color to generate. Must be >= 0.
 * @param seedHues A non-empty list of seed hues to base the color generation on.
 * @param isDark Whether the color is for dark mode (true) or light mode (false).
 * @param tuning Optional tuning parameters for the categorical color generation.
 * @return A [BasisColor] representing the generated categorical color.
 * @throws IllegalArgumentException if [index] is negative or [seedHues] is empty.
 */
fun categoricalColor(
    index: Int,
    seedHues: List<BasisColor>,
    isDark: Boolean,
    tuning: BasisCategoricalTuning = BasisCategoricalTuning(),
): BasisColor {
    require(index >= 0) { "categoricalColor index must be >= 0, got $index" }
    require(seedHues.isNotEmpty()) { "categoricalColor requires at least one seed hue." }

    val anchors = seedHues.map { it.toOklch() }
    val fixedChroma = anchors.maxOf { it.c }.coerceAtLeast(tuning.paletteMinChroma)
    val hue = if (index < anchors.size) {
        anchors[index].h
    } else {
        val overflowSteps = index - anchors.size + 1
        anchors.last().rotateHue(GOLDEN_ANGLE_DEGREES * overflowSteps).h
    }

    val lightness = if (isDark) tuning.paletteLightnessDark else tuning.paletteLightnessLight
    return Oklch(lightness, fixedChroma, hue).toBasisColor()
}

/**
 * Builds a list of contrast-safe categorical colors for one mode, given a non-empty list of seed hues.
 *
 * @param seedHues A non-empty list of seed hues to base the color generation on.
 * @param count The number of colors to generate. Must be > 0.
 * @param isDark Whether the colors are for dark mode (true) or light mode (false).
 * @param tuning Optional tuning parameters for the categorical color generation.
 * @return A list of [BasisColor] representing the generated categorical colors.
 * @throws IllegalArgumentException if [count] is not positive or [seedHues] is empty.
 */
fun categoricalPalette(
    seedHues: List<BasisColor>,
    count: Int,
    isDark: Boolean,
    tuning: BasisCategoricalTuning = BasisCategoricalTuning(),
): List<BasisColor> {
    require(count > 0) { "categoricalPalette count must be > 0, got $count" }
    return (0 until count).map { categoricalColor(it, seedHues, isDark, tuning) }
}

/**
 * Builds a "soft" variant of the given categorical colors, adjusting lightness and chroma for a muted
 * appearance.
 *
 * Hue is preserved so that a soft series still reads as the same categories, just recessive — suitable
 * for chart backgrounds, legends, and any place where the data itself must dominate.
 *
 * @param colors The list of categorical colors to soften.
 * @param isDark Whether the colors are for dark mode (true) or light mode (false).
 * @param tuning Optional tuning parameters for the categorical color generation.
 * @return A list of [BasisColor] representing the softened categorical colors, in the same order as [colors].
 */
fun softVariant(
    colors: List<BasisColor>,
    isDark: Boolean,
    tuning: BasisCategoricalTuning = BasisCategoricalTuning(),
): List<BasisColor> {
    val lightness = if (isDark) tuning.softLightnessDark else tuning.softLightnessLight
    return colors.map { color ->
        val oklch = color.toOklch()
        Oklch(l = lightness, c = oklch.c * tuning.softChromaScale, h = oklch.h).toBasisColor()
    }
}

/**
 * Returns the safe contrast content color to place on [color].
 *
 * Picks whichever of the inverse or default content colors contrasts better against the given
 * background, so callers never have to reason about the background's lightness by hand.
 *
 * @param color The background color that content will be drawn on.
 * @return A [BasisColor] guaranteed to be legible on [color].
 */
fun contentOn(color: BasisColor): BasisColor = color.contentOn()
